### ISSUE TITLE
Register 0.3.7

### ISSUE THREAD

**Issue by ChrisRackauckas** [staticfloat/ObjectFile.jl#31]
Looks like the registration failed, so this package holds back Reexport 1

**Comment by giordano** [comment]
@staticfloat

**Comment by giordano** [comment]
Out of curiosity, how come you have `ObjectFile` in your environment? :smile:  There so few packages using it.  Maybe Enzyme?

**Comment by ChrisRackauckas** [comment]
Playing with Enzyme: https://github.com/SciML/DiffEqSensitivity.jl/pull/427

**Comment by wsmoses** [comment]
Yeah the reason we use objectfile is to parse the LLVM embedded bitcode of libraries if it exists and attempt to AD through a ccall :P
